name: Auto Label Based on Branch Name

permissions:
  issues: write
  pull-requests: read

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const branch = context.payload.pull_request.head.ref;
            const prefix = branch.split('/')[0];
            const label = prefix.toLowerCase();

            const labels = await github.rest.issues.listLabelsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const labelNames = labels.data.map(l => l.name.toLowerCase());

            if (labelNames.includes(label)) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: [label]
              });
              console.log(`Applied label: ${label}`);
            } else {
              console.log(`Label "${label}" not found in repo; skipping.`);
            }