name: Auto Label Based on Branch Name

permissions:
  contents: write
  issues: write
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const branch = context.payload.pull_request.head.ref;
            const prefix = branch.split('/')[0];
            const label = prefix.toLowerCase();

            const labels = await github.rest.issues.listLabelsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const labelNames = labels.data.map(l => l.name.toLowerCase());

            if (labelNames.includes(label)) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: [label]
              });
              console.log(`Applied label: ${label}`);
            } else {
              console.log(`Label "${label}" not found in repo; skipping.`);
            }
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: |
            maintenance
            bug
            feature
            enhancement
            documentation
          add_comment: true
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 0
          labels: "do not merge"
          add_comment: true
