name: Create Release on Master Push

permissions:
  contents: write

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build Release Artifacts
        run: make release

      - name: Archive Binaries per OS/Arch
        env:
          # Set the name of the binary as built by your Makefile.
          BINARY_NAME: cloudflare-dyndns
        run: |
          # Loop over each OS and architecture directory under bin/
          for os in $(ls bin); do
            for arch in $(ls bin/$os); do
              if [ "$os" = "windows" ]; then
                echo "Archiving for $os $arch as zip"
                zip -j "${os}-${arch}.zip" "bin/$os/$arch/$BINARY_NAME"
              else
                echo "Archiving for $os $arch as tar.gz"
                tar -C "bin/$os/$arch" -czvf "${os}-${arch}.tar.gz" "$BINARY_NAME"
              fi
            done
          done

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ github.run_number }}"
          release_name: "Release ${{ github.run_number }}"
          body: "Automated release generated on push to master."
          draft: false
          prerelease: false

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Strip the templated part from the upload URL.
          upload_url="${{ steps.create_release.outputs.upload_url }}"
          upload_url="${upload_url%\{*}"

          # Loop over generated archives
          for asset in *.tar.gz *.zip; do
            if [ -f "$asset" ]; then
              echo "Uploading $asset"
              if [[ "$asset" == *.zip ]]; then
                content_type="application/zip"
              else
                content_type="application/gzip"
              fi
              # URL‑encode the asset name (ensure python3 is available on the runner)
              encoded_name=$(python3 -c "import urllib.parse; print(urllib.parse.quote('''$asset'''))")
              curl --fail -X POST \
                -H "Authorization: token $GITHUB_TOKEN" \
                -H "Content-Type: ${content_type}" \
                --data-binary @"$asset" \
                "${upload_url}?name=${encoded_name}"
            fi
          done