name: Create Release on Tag

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0  # Fetch all branches

      - name: Generate Changelog with Release Drafter
        uses: release-drafter/release-drafter@v6.1.0
        id: generate_changelog
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Up Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version: '1.24'

      - name: Go Version
        run: go version
        continue-on-error: true

      - name: Build Release Artifacts
        run: make release-all

      - name: Archive Binaries per OS/Arch
        env:
          BINARY_NAME: cloudflare-dyndns
        run: |
          for os in $(ls bin); do
            for arch in $(ls bin/$os); do
              if [ "$os" = "windows" ]; then
                echo "Archiving for $os $arch as zip"
                # Append .exe for windows
                zip -j "${os}-${arch}.zip" "bin/release/$os/$arch/${BINARY_NAME}.exe"
              else
                echo "Archiving for $os $arch as tar.gz"
                tar -C "bin/release/$os/$arch" -czvf "${os}-${arch}.tar.gz" "$BINARY_NAME"
              fi
            done
          done

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: |
            ${{ steps.generate_changelog.outputs.body }}
          draft: false
          prerelease: false

      - name: Install GitHub CLI (just in case)
        run: sudo apt-get update && sudo apt-get install gh -y

      - name: Upload Release Assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "${{ github.ref_name }}" *.tar.gz *.zip
