name: Create Release on Master Push

permissions:
  contents: write

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate release tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: 'v'
          tag_template: 'yyyy.mm.dd.i'

      - name: Generate changelog
        uses: Bullrich/generate-release-changelog@master
        id: generate_changelog
        env:
          REPO: ${{ github.repository }}

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Run go mod tidy
        run: go mod tidy

      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          # Caching both module downloads and build cache
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build Release Artifacts
        run: make release-all

      - name: Archive Binaries per OS/Arch
        env:
          BINARY_NAME: cloudflare-dyndns
        run: |
          for os in $(ls bin); do
            for arch in $(ls bin/$os); do
              if [ "$os" = "windows" ]; then
                echo "Archiving for $os $arch as zip"
                # Append .exe for windows
                zip -j "${os}-${arch}.zip" "bin/$os/$arch/${BINARY_NAME}.exe"
              else
                echo "Archiving for $os $arch as tar.gz"
                tar -C "bin/$os/$arch" -czvf "${os}-${arch}.tar.gz" "$BINARY_NAME"
              fi
            done
          done

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.generate_release_tag.outputs.next_release_tag }}
          release_name: ${{ steps.generate_release_tag.outputs.next_release_tag }}
          body: |
            ${{ steps.generate_changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Strip the templated part from the upload URL.
          upload_url="${{ steps.create_release.outputs.upload_url }}"
          upload_url="${upload_url%\{*}"

          # Loop over generated archives.
          for asset in *.tar.gz *.zip; do
            if [ -f "$asset" ]; then
              echo "Uploading $asset"
              if [[ "$asset" == *.zip ]]; then
                content_type="application/zip"
              else
                content_type="application/gzip"
              fi
              # URL‑encode the asset name.
              encoded_name=$(python3 -c "import urllib.parse; print(urllib.parse.quote('''$asset'''))")
              curl --fail -X POST \
                -H "Authorization: token $GITHUB_TOKEN" \
                -H "Content-Type: ${content_type}" \
                --data-binary @"$asset" \
                "${upload_url}?name=${encoded_name}"
            fi
          done